### PR TITLE
Replaced static dawn libs with dynamic ones

### PR DESCRIPTION
**Pull request by ilijapuaca**
Was not able to link against static libraries, linking fails because `GetProcsAutogen` symbol is missing. There were issues with making use of dynamic libs as well, added an additional note to `iOS-BUILD.md`

### CODE REVIEW

**Comment by isaacbrodsky** [comment]
Does ` docs/iOS-BUILD.md` need a note on changing dawn to static builds?

**Comment by ilijapuaca** [comment]
This PR makes the switch from static to dynamic libs, which now aligns with the rest of the OSs. Building dawn builds both in either configuration

**Comment by ibgreen** [comment]
Should we squash the history of this repo when we release so that we get rid of all the temporary binaries?

**Comment by ilijapuaca** [comment]
> Should we squash the history of this repo when we release so that we get rid of all the temporary binaries?

Done on `master`

**Pull request merged**
